In [9]:
import pandas as pd
pd.read_csv("/Users/ramon/Desktop/Ironhack/June/Project-Week-2-Barcelona/datasets/3.-Population/deaths.csv")

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,0-4,1
1,2017,1,Ciutat Vella,2,el Barri Gòtic,0-4,1
2,2017,1,Ciutat Vella,3,la Barceloneta,0-4,0
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",0-4,0
4,2017,2,Eixample,5,el Fort Pienc,0-4,0
...,...,...,...,...,...,...,...
4594,2015,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,>=100,1
4595,2015,10,Sant Martí,70,el Besòs i el Maresme,>=100,3
4596,2015,10,Sant Martí,71,Provençals del Poblenou,>=100,2
4597,2015,10,Sant Martí,72,Sant Martí de Provençals,>=100,1
4598,2015,10,Sant Martí,73,la Verneda i la Pau,>=100,8

In [10]:
pd.read_csv("/Users/ramon/Desktop/Ironhack/June/Project-Week-2-Barcelona/datasets/3.-Population/births.csv")

,Year,District Code,District Name,Neighborhood Code,Neighborhood Name,Gender,Number
0,2017,1,Ciutat Vella,1,el Raval,Boys,283
1,2017,1,Ciutat Vella,2,el Barri Gòtic,Boys,56
2,2017,1,Ciutat Vella,3,la Barceloneta,Boys,51
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Boys,90
4,2017,2,Eixample,5,el Fort Pienc,Boys,117
...,...,...,...,...,...,...,...
729,2013,10,Sant Martí,70,el Besòs i el Maresme,Girls,93
730,2013,10,Sant Martí,71,Provençals del Poblenou,Girls,95
731,2013,10,Sant Martí,72,Sant Martí de Provençals,Girls,97
732,2013,10,Sant Martí,73,la Verneda i la Pau,Girls,94
733,2013,99,No consta,99,No consta,Girls,2

In [11]:
pd.read_csv("/Users/ramon/Desktop/Ironhack/June/Project-Week-2-Barcelona/datasets/3.-Population/immigrants-by-nationality.csv")

,Year,District Code,District Name,Neighborhood Code,Neighborhood Name,Nationality,Number
0,2017,1,Ciutat Vella,1,el Raval,Spain,1109
1,2017,1,Ciutat Vella,2,el Barri Gòtic,Spain,482
2,2017,1,Ciutat Vella,3,la Barceloneta,Spain,414
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Spain,537
4,2017,2,Eixample,5,el Fort Pienc,Spain,663
...,...,...,...,...,...,...,...
35219,2015,10,Sant Martí,70,el Besòs i el Maresme,No information,0
35220,2015,10,Sant Martí,71,Provençals del Poblenou,No information,0
35221,2015,10,Sant Martí,72,Sant Martí de Provençals,No information,0
35222,2015,10,Sant Martí,73,la Verneda i la Pau,No information,1
35223,2015,99,No consta,99,No consta,No information,0

In [12]:
pd.read_csv("/Users/ramon/Desktop/Ironhack/June/Project-Week-2-Barcelona/datasets/3.-Population/immigrants-emigrants-by-age.csv")

,Year,District Code,District Name,Neighborhood Code,Neighborhood Name,Age,Immigrants,Emigrants
0,2017,1,Ciutat Vella,1,el Raval,0-4,154,108
1,2017,1,Ciutat Vella,2,el Barri Gòtic,0-4,58,33
2,2017,1,Ciutat Vella,3,la Barceloneta,0-4,38,37
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",0-4,56,55
4,2017,2,Eixample,5,el Fort Pienc,0-4,79,60
...,...,...,...,...,...,...,...,...
4657,2015,10,Sant Martí,70,el Besòs i el Maresme,>=100,0,1
4658,2015,10,Sant Martí,71,Provençals del Poblenou,>=100,0,0
4659,2015,10,Sant Martí,72,Sant Martí de Provençals,>=100,0,0
4660,2015,10,Sant Martí,73,la Verneda i la Pau,>=100,0,0
4661,2015,99,No consta,99,No consta,>=100,0,0

In [13]:
pd.read_csv("/Users/ramon/Desktop/Ironhack/June/Project-Week-2-Barcelona/datasets/3.-Population/immigrants-emigrants-by-destination.csv")

                   from                   to  weight
0                Abroad            Barcelona   53085
1             Andalusia            Barcelona    2416
2                Aragon            Barcelona     811
3              Asturias            Barcelona     323
4      Balearic Islands            Barcelona    1634
5             Barcelona               Abroad    5485
6             Barcelona            Andalusia    1596
7             Barcelona               Aragon     745
8             Barcelona             Asturias     204
9             Barcelona     Balearic Islands    1428
10            Barcelona       Basque Country     475
11            Barcelona       Canary Islands     789
12            Barcelona            Cantabria     132
13            Barcelona     Castile and León     517
14            Barcelona   Castilla-La Mancha     347
15            Barcelona            Catalonia   35036
16            Barcelona                Ceuta      12
17            Barcelona  Community of Madrid    2647
18            Barcelona          Extremadura     201
19            Barcelona              Galicia     795
20            Barcelona             La Rioja      72
21            Barcelona              Melilla      27
22            Barcelona              Navarre     186
23            Barcelona     Region of Murcia     243
24            Barcelona  Valencian Community    1711
25       Basque Country            Barcelona     710
26       Canary Islands            Barcelona     863
27            Cantabria            Barcelona     162
28     Castile and León            Barcelona     814
29   Castilla-La Mancha            Barcelona     445
30            Catalonia            Barcelona   28779
31                Ceuta            Barcelona      24
32  Community of Madrid            Barcelona    2942
33          Extremadura            Barcelona     240
34              Galicia            Barcelona     983
35             La Rioja            Barcelona     129
36              Melilla            Barcelona      60
37              Navarre            Barcelona     246
38     Region of Murcia            Barcelona     354
39  Valencian Community            Barcelona    2305

In [14]:
pd.read_csv("/Users/ramon/Desktop/Ironhack/June/Project-Week-2-Barcelona/datasets/3.-Population/immigrants-emigrants-by-sex.csv")

,Year,District Code,District Name,Neighborhood Code,Neighborhood Name,Gender,Immigrants,Emigrants
0,2017,1,Ciutat Vella,1,el Raval,Male,3063,1195
1,2017,1,Ciutat Vella,2,el Barri Gòtic,Male,1499,427
2,2017,1,Ciutat Vella,3,la Barceloneta,Male,910,361
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Male,1438,502
4,2017,2,Eixample,5,el Fort Pienc,Male,1082,495
...,...,...,...,...,...,...,...,...
725,2013,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,Female,261,206
726,2013,10,Sant Martí,70,el Besòs i el Maresme,Female,568,455
727,2013,10,Sant Martí,71,Provençals del Poblenou,Female,360,305
728,2013,10,Sant Martí,72,Sant Martí de Provençals,Female,446,355
729,2013,10,Sant Martí,73,la Verneda i la Pau,Female,505,426

In [15]:
pd.read_csv("/Users/ramon/Desktop/Ironhack/June/Project-Week-2-Barcelona/datasets/3.-Population/population.csv")

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Gender,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,Male,0-4,224
1,2017,1,Ciutat Vella,2,el Barri Gòtic,Male,0-4,50
2,2017,1,Ciutat Vella,3,la Barceloneta,Male,0-4,43
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Male,0-4,95
4,2017,2,Eixample,5,el Fort Pienc,Male,0-4,124
...,...,...,...,...,...,...,...,...
70075,2013,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,Female,>=95,21
70076,2013,10,Sant Martí,70,el Besòs i el Maresme,Female,>=95,25
70077,2013,10,Sant Martí,71,Provençals del Poblenou,Female,>=95,31
70078,2013,10,Sant Martí,72,Sant Martí de Provençals,Female,>=95,38
70079,2013,10,Sant Martí,73,la Verneda i la Pau,Female,>=95,47

In [16]:
#We now keep only the data from 2017:
immigrants_by_nationality_2017 = immigrants_by_nationality[immigrants_by_nationality["Year"] == 2017]
population_2017 = population[population["Year"] == 2017]
deaths_2017 = deaths[deaths["Year"] == 2017]
immigrants_emigrants_by_sex_2017 = immigrants_emigrants_by_sex[immigrants_emigrants_by_sex["Year"] == 2017]
immigrants_emigrants_by_age_2017 = immigrants_emigrants_by_age[immigrants_emigrants_by_age["Year"] == 2017]
births_2017 = births[births["Year"] == 2017]

NameError: name 'immigrants_by_nationality' is not defined

In [17]:
#We first import the pandas library and the provided data
import pandas as pd
import os
sources_list = [file for file in os.listdir('../Sources/3.-Population/') if file.endswith('.csv')]
print(sources_list)
for file in sources_list:
    globals()[file[:-4]] = pd.read_csv('../Sources/3.-Population/' + file)

['births.csv', 'deaths.csv', 'immigrants_by_nationality.csv', 'immigrants_emigrants_by_age.csv', 'immigrants_emigrants_by_destination.csv', 'immigrants_emigrants_by_sex.csv', 'most_frequent_baby_names.csv', 'most_frequent_names.csv', 'population.csv']

In [18]:
#We import external data
external = [file for file in os.listdir('../Sources/External_sources/') if file.endswith('.csv')]
print(external)
for file in external:
    globals()[file[:-4]] = pd.read_csv('../Sources/External_sources/' + file)

['_distribucio_territorial_renda_familiar.csv', '_est_salut_publica_esp_vida.csv']

In [19]:
deaths.head()

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,0-4,1
1,2017,1,Ciutat Vella,2,el Barri Gòtic,0-4,1
2,2017,1,Ciutat Vella,3,la Barceloneta,0-4,0
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",0-4,0
4,2017,2,Eixample,5,el Fort Pienc,0-4,0

In [20]:
#Change renta dataset column - Codi Barri to the same on as the all other's data sets "Neighborhood.Code"
_distribucio_territorial_renda_familiar.head()
print(_distribucio_territorial_renda_familiar.columns)
_distribucio_territorial_renda_familiar.rename(columns={"Codi_Barri":"Neighborhood.Code"},inplace=True)

Index(['Any', 'Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'Nom_Barri',
       'Població', 'Índex RFD Barcelona = 100'],
      dtype='object')

In [21]:
#All datasets share the same variable Neighborhood code
_distribucio_territorial_renda_familiar.Any.value_counts()

2017    73
Name: Any, dtype: int64

In [22]:
#We merge deaths with familiar rent
merged=pd.merge(deaths,_distribucio_territorial_renda_familiar,how="right",on="Neighborhood.Code")
merged=merged[merged["Year"]==2017]
print(merged.columns)
merged.head(30)
#Atorgant a la renda mitjana de Barcelona un valor de 100, els barris de renda molt baixa són el que tenen una renda inferior a 63, els de renda baixa, de 63 a 79, els de renda mitjana-baixa, de 79 a 100, els de renda mitjana-alta, de 100 a 126, els de renda alta de 126 a 159 i els de renda molt alta, superior a 159.

Index(['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Age', 'Number', 'Any', 'Codi_Districte',
       'Nom_Districte', 'Nom_Barri', 'Població', 'Índex RFD Barcelona = 100'],
      dtype='object')

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number,Any,Codi_Districte,Nom_Districte,Nom_Barri,Població,Índex RFD Barcelona = 100
0,2017,1,Ciutat Vella,1,el Raval,0-4,1,2017,1,Ciutat Vella,el Raval,47986,71.2
1,2017,1,Ciutat Vella,1,el Raval,5-9,0,2017,1,Ciutat Vella,el Raval,47986,71.2
2,2017,1,Ciutat Vella,1,el Raval,10-14,0,2017,1,Ciutat Vella,el Raval,47986,71.2
3,2017,1,Ciutat Vella,1,el Raval,15-19,0,2017,1,Ciutat Vella,el Raval,47986,71.2
4,2017,1,Ciutat Vella,1,el Raval,20-24,0,2017,1,Ciutat Vella,el Raval,47986,71.2
5,2017,1,Ciutat Vella,1,el Raval,25-29,1,2017,1,Ciutat Vella,el Raval,47986,71.2
6,2017,1,Ciutat Vella,1,el Raval,30-34,2,2017,1,Ciutat Vella,el Raval,47986,71.2
7,2017,1,Ciutat Vella,1,el Raval,35-39,2,2017,1,Ciutat Vella,el Raval,47986,71.2
8,2017,1,Ciutat Vella,1,el Raval,40-44,9,2017,1,Ciutat Vella,el Raval,47986,71.2
9,2017,1,Ciutat Vella,1,el Raval,45-49,14,2017,1,Ciutat Vella,el Raval,47986,71.2
10,2017,1,Ciutat Vella,1,el Raval,50-54,12,2017,1,Ciutat Vella,el Raval,47986,71.2
11,2017,1,Ciutat Vella,1,el Raval,55-59,11,2017,1,Ciutat Vella,el Raval,47986,71.2
12,2017,1,Ciutat Vella,1,el Raval,60-64,16,2017,1,Ciutat Vella,el Raval,47986,71.2
13,2017,1,Ciutat Vella,1,el Raval,65-69,25,2017,1,Ciutat Vella,el Raval,47986,71.2
14,2017,1,Ciutat Vella,1,el Raval,70-74,21,2017,1,Ciutat Vella,el Raval,47986,71.2
15,2017,1,Ciutat Vella,1,el Raval,75-79,32,2017,1,Ciutat Vella,el Raval,47986,71.2
16,2017,1,Ciutat Vella,1,el Raval,80-84,68,2017,1,Ciutat Vella,el Raval,47986,71.2
17,2017,1,Ciutat Vella,1,el Raval,85-89,52,2017,1,Ciutat Vella,el Raval,47986,71.2
18,2017,1,Ciutat Vella,1,el Raval,90-94,57,2017,1,Ciutat Vella,el Raval,47986,71.2
19,2017,1,Ciutat Vella,1,el Raval,95-99,17,2017,1,Ciutat Vella,el Raval,47986,71.2
20,2017,1,Ciutat Vella,1,el Raval,>=100,6,2017,1,Ciutat Vella,el Raval,47986,71.2
63,2017,1,Ciutat Vella,2,el Barri Gòtic,0-4,1,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1
64,2017,1,Ciutat Vella,2,el Barri Gòtic,5-9,0,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1
65,2017,1,Ciutat Vella,2,el Barri Gòtic,10-14,0,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1
66,2017,1,Ciutat Vella,2,el Barri Gòtic,15-19,0,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1
67,2017,1,Ciutat Vella,2,el Barri Gòtic,20-24,0,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1
68,2017,1,Ciutat Vella,2,el Barri Gòtic,25-29,0,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1
69,2017,1,Ciutat Vella,2,el Barri Gòtic,30-34,1,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1
70,2017,1,Ciutat Vella,2,el Barri Gòtic,35-39,1,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1
71,2017,1,Ciutat Vella,2,el Barri Gòtic,40-44,0,2017,1,Ciutat Vella,el Barri Gòtic,16240,106.1

In [23]:
#We now keep only the data from 2017:
immigrants_by_nationality_2017 = immigrants_by_nationality[immigrants_by_nationality["Year"] == 2017]
population_2017 = population[population["Year"] == 2017]
deaths_2017 = deaths[deaths["Year"] == 2017]
immigrants_emigrants_by_sex_2017 = immigrants_emigrants_by_sex[immigrants_emigrants_by_sex["Year"] == 2017]
immigrants_emigrants_by_age_2017 = immigrants_emigrants_by_age[immigrants_emigrants_by_age["Year"] == 2017]
births_2017 = births[births["Year"] == 2017]

In [24]:
#We gropued the ages deatsh csv by interval of 19 instead of 4
rangs = [["0-19","0-4","5-9","10-14","15-19"],["20-39","20-24","25-29","30-34","35-39"],["40-59","40-44","45-49","50-54","55-59"],["60-79","60-64","65-69","70-74","75-79"],["+80","80-84","85-89","90-94","95-99",">=100"]]
deaths_ages_grouped = deaths_2017.copy()
for i in range(len(deaths_ages_grouped["Age"])):
    for r in rangs:
        if deaths_ages_grouped["Age"][i] in r:
            deaths_ages_grouped["Age"][i] = r[0]

C:\Users\ramon\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [25]:
#Most deaths on 2017 by age, neig and dist
deaths_ages_grouped.groupby(["District.Name","Neighborhood.Name","Age"])[["Number"]].sum().sort_values("Number",ascending = False)

                                                       Number
District.Name Neighborhood.Name                 Age
Eixample      la Nova Esquerra de l'Eixample    +80       404
              la Dreta de l'Eixample            +80       390
              la Sagrada Família                +80       382
Gràcia        la Vila de Gràcia                 +80       372
Sant Andreu   Sant Andreu                       +80       340
...                                                       ...
Nou Barris    Torre Baró                        0-19        0
Sant Martí    el Poblenou                       0-19        0
              el Parc i la Llacuna del Poblenou 0-19        0
Gràcia        Vallcarca i els Penitents         20-39       0
Sant Andreu   la Trinitat Vella                 20-39       0

[365 rows x 1 columns]

In [26]:
#Most death by neigh <40
deaths_ages_grouped[(deaths_ages_grouped["Age"] == rangs[0][0]) | (deaths_ages_grouped["Age"] == rangs[1][0])].groupby(["District.Name","Neighborhood.Name","Age"])[["Number"]].sum().sort_values("Number",ascending = False).head(20)

                                                      Number
District.Name  Neighborhood.Name               Age
Ciutat Vella   el Raval                        20-39       5
Sants-Montjuïc la Marina de Port               20-39       5
Nou Barris     Vilapicina i la Torre Llobeta   20-39       4
Les Corts      la Maternitat i Sant Ramon      20-39       4
Eixample       l'Antiga Esquerra de l'Eixample 20-39       4
               la Dreta de l'Eixample          20-39       3
Horta-Guinardó el Carmel                       20-39       3
Sant Martí     el Clot                         20-39       3
Horta-Guinardó Horta                           20-39       3
Sant Martí     la Verneda i la Pau             20-39       3
Gràcia         la Vila de Gràcia               0-19        3
Sant Andreu    la Sagrera                      0-19        3
Les Corts      les Corts                       20-39       3
Nou Barris     la Prosperitat                  20-39       3
Eixample       la Nova Esquerra de l'Eixample  20-39       3
Sant Andreu    el Congrés i els Indians        20-39       3
Eixample       el Fort Pienc                   20-39       3
                                               0-19        3
Nou Barris     el Turó de la Peira             20-39       2
Sants-Montjuïc la Font de la Guatlla           20-39       2

In [27]:
#Apply the same changes for range "Age" to the population dataframe
rangs = [["0-19","0-4","5-9","10-14","15-19"],["20-39","20-24","25-29","30-34","35-39"],["40-59","40-44","45-49","50-54","55-59"],["60-79","60-64","65-69","70-74","75-79"],["+80","80-84","85-89","90-94","95-99",">=100"]]
population_grouped = population_2017.copy()
for i in range(len(population_grouped["Age"])):
    for r in rangs:
        if population_grouped["Age"][i] in r:
            population_grouped["Age"][i] = r[0]

C:\Users\ramon\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [28]:
#Most populated districts from barcelona
population_grouped.groupby(["District.Name","Neighborhood.Name"]).sum()[["Number"]].sort_values("Number",ascending = False).head(25)

                                                        Number
District.Name       Neighborhood.Name
Eixample            la Nova Esquerra de l'Eixample       58180
Sant Andreu         Sant Andreu                          57183
Eixample            la Sagrada Família                   51539
Gràcia              la Vila de Gràcia                    50662
Sarrià-Sant Gervasi Sant Gervasi - Galvany               47666
Ciutat Vella        el Raval                             47608
Les Corts           les Corts                            46009
Eixample            la Dreta de l'Eixample               44052
                    l'Antiga Esquerra de l'Eixample      42284
Sants-Montjuïc      Sants                                41127
                    el Poble Sec                         40228
Eixample            Sant Antoni                          38345
Sant Martí          el Camp de l'Arpa del Clot           38168
Horta-Guinardó      el Guinardó                          36467
Gràcia              el Camp d'en Grassot i Gràcia Nova   34329
Sant Martí          el Poblenou                          33843
Eixample            el Fort Pienc                        32016
Horta-Guinardó      el Carmel                            31551
Sants-Montjuïc      la Marina de Port                    30584
Sarrià-Sant Gervasi el Putxet i el Farró                 29470
Sant Andreu         la Sagrera                           29084
Sant Martí          la Verneda i la Pau                  28691
                    el Clot                              27039
Horta-Guinardó      Horta                                26715
Nou Barris          la Prosperitat                       26389

In [29]:
#Merged death ages with rent
merged_death_rent=pd.merge(deaths_ages_grouped,_distribucio_territorial_renda_familiar,how="right",on="Neighborhood.Code")
merged_death_rent=merged_death_rent[merged_death_rent["Year"]==2017]
print(merged_death_rent.columns)
merged_death_rent.head()

Index(['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Age', 'Number', 'Any', 'Codi_Districte',
       'Nom_Districte', 'Nom_Barri', 'Població', 'Índex RFD Barcelona = 100'],
      dtype='object')

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number,Any,Codi_Districte,Nom_Districte,Nom_Barri,Població,Índex RFD Barcelona = 100
0,2017,1,Ciutat Vella,1,el Raval,0-19,1,2017,1,Ciutat Vella,el Raval,47986,71.2
1,2017,1,Ciutat Vella,1,el Raval,0-19,0,2017,1,Ciutat Vella,el Raval,47986,71.2
2,2017,1,Ciutat Vella,1,el Raval,0-19,0,2017,1,Ciutat Vella,el Raval,47986,71.2
3,2017,1,Ciutat Vella,1,el Raval,0-19,0,2017,1,Ciutat Vella,el Raval,47986,71.2
4,2017,1,Ciutat Vella,1,el Raval,20-39,0,2017,1,Ciutat Vella,el Raval,47986,71.2

In [30]:
merged_death_rent[(merged_death_rent["Age"] == rangs[0][0]) | (merged_death_rent["Age"] == rangs[1][0])].groupby(["District.Name","Neighborhood.Name","Age","Índex RFD Barcelona = 100"])[["Number"]].sum().sort_values("Number",ascending = False).head(20)

                                                                                Number
District.Name  Neighborhood.Name               Age   Índex RFD Barcelona = 100
Ciutat Vella   el Raval                        20-39 71.2                            5
Sants-Montjuïc la Marina de Port               20-39 69.3                            5
Nou Barris     Vilapicina i la Torre Llobeta   20-39 63.8                            4
Les Corts      la Maternitat i Sant Ramon      20-39 114.2                           4
Eixample       l'Antiga Esquerra de l'Eixample 20-39 137.2                           4
               la Dreta de l'Eixample          20-39 175.9                           3
Horta-Guinardó el Carmel                       20-39 54.2                            3
Sant Martí     el Clot                         20-39 83.6                            3
Horta-Guinardó Horta                           20-39 79.8                            3
Sant Martí     la Verneda i la Pau             20-39 57.0                            3
Gràcia         la Vila de Gràcia               0-19  104.4                           3
Sant Andreu    la Sagrera                      0-19  77.1                            3
Les Corts      les Corts                       20-39 120.0                           3
Nou Barris     la Prosperitat                  20-39 56.0                            3
Eixample       la Nova Esquerra de l'Eixample  20-39 110.2                           3
Sant Andreu    el Congrés i els Indians        20-39 75.1                            3
Eixample       el Fort Pienc                   20-39 106.5                           3
                                               0-19  106.5                           3
Nou Barris     el Turó de la Peira             20-39 51.9                            2
Sants-Montjuïc la Font de la Guatlla           20-39 82.9                            2

In [31]:
merged_death_rent.drop("Nom_Districte",axis=1,inplace=True)
merged_death_rent.drop("Nom_Barri",axis=1,inplace=True)

In [32]:
merged_death_rent.drop("Any",axis=1,inplace=True)

In [33]:
vida = _est_salut_publica_esp_vida.copy()
vida2017 = vida[vida.Anys_Periode == '2013-2017']
vida2017

,Anys_Periode,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Nombre
511,2013-2017,1,Ciutat Vella,1,el Raval,81.3
512,2013-2017,1,Ciutat Vella,2,el Barri Gòtic,81.8
513,2013-2017,1,Ciutat Vella,3,la Barceloneta,80.7
514,2013-2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",82.8
515,2013-2017,2,Eixample,5,el Fort Pienc,84.5
...,...,...,...,...,...,...
579,2013-2017,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,85.6
580,2013-2017,10,Sant Martí,70,el Besòs i el Maresme,84.3
581,2013-2017,10,Sant Martí,71,Provençals del Poblenou,85.2
582,2013-2017,10,Sant Martí,72,Sant Martí de Provençals,85.0
583,2013-2017,10,Sant Martí,73,la Verneda i la Pau,84.4

In [34]:
vida2017.drop("Anys_Periode",axis=1,inplace=True)

C:\Users\ramon\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [35]:
vida2017.columns = ['Codi_Districte', 'Nom_Districte', 'Neighborhood.Code', 'Nom_Barri', 'Nombre']
vida2017

,Codi_Districte,Nom_Districte,Neighborhood.Code,Nom_Barri,Nombre
511,1,Ciutat Vella,1,el Raval,81.3
512,1,Ciutat Vella,2,el Barri Gòtic,81.8
513,1,Ciutat Vella,3,la Barceloneta,80.7
514,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",82.8
515,2,Eixample,5,el Fort Pienc,84.5
...,...,...,...,...,...
579,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,85.6
580,10,Sant Martí,70,el Besòs i el Maresme,84.3
581,10,Sant Martí,71,Provençals del Poblenou,85.2
582,10,Sant Martí,72,Sant Martí de Provençals,85.0
583,10,Sant Martí,73,la Verneda i la Pau,84.4

In [36]:
merged_death_rent=pd.merge(merged_death_rent,vida2017,how="left",on="Neighborhood.Code")
merged_death_rent=merged_death_rent[merged_death_rent["Year"]==2017]
print(merged_death_rent.columns)
merged_death_rent.tail()

Index(['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Age', 'Number', 'Codi_Districte_x', 'Població',
       'Índex RFD Barcelona = 100', 'Codi_Districte_y', 'Nom_Districte',
       'Nom_Barri', 'Nombre'],
      dtype='object')

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Age,Number,Codi_Districte_x,Població,Índex RFD Barcelona = 100,Codi_Districte_y,Nom_Districte,Nom_Barri,Nombre
1528,2017,10,Sant Martí,73,la Verneda i la Pau,+80,66,10,28725,57.0,10,Sant Martí,la Verneda i la Pau,84.4
1529,2017,10,Sant Martí,73,la Verneda i la Pau,+80,72,10,28725,57.0,10,Sant Martí,la Verneda i la Pau,84.4
1530,2017,10,Sant Martí,73,la Verneda i la Pau,+80,62,10,28725,57.0,10,Sant Martí,la Verneda i la Pau,84.4
1531,2017,10,Sant Martí,73,la Verneda i la Pau,+80,16,10,28725,57.0,10,Sant Martí,la Verneda i la Pau,84.4
1532,2017,10,Sant Martí,73,la Verneda i la Pau,+80,3,10,28725,57.0,10,Sant Martí,la Verneda i la Pau,84.4

In [37]:
merged_death_rent.drop("Codi_Districte_x",axis=1,inplace=True)
merged_death_rent.drop("Codi_Districte_y",axis=1,inplace=True)

In [38]:
merged_death_rent.columns

Index(['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Age', 'Number', 'Població',
       'Índex RFD Barcelona = 100', 'Nom_Districte', 'Nom_Barri', 'Nombre'],
      dtype='object')

In [43]:
#Eliminate Columns,DON'T RUN AGAIN
#merged_death_rent.drop("Nom_Districte_x",axis=1,inplace=True)
#merged_death_rent.drop("Nom_Barri_x",axis=1,inplace=True)
#merged_death_rent.drop("Nom_Districte_y",axis=1,inplace=True)
#merged_death_rent.drop("Nom_Barri_y",axis=1,inplace=True)
#merged_death_rent.drop("Nombre",axis=1,inplace=True)

In [44]:
#Eliminate Columns,DON'T RUN AGAIN
#merged_death_rent.drop("Codi_Districte",axis=1,inplace=True)

In [46]:
merged_death_rent.columns = ['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Age', 'Nº Deaths', 'Population',
       'Índex RFD Barcelona = 100', 'Nom_Districte', 'Nom_Barri', 'Life Expectancy']

In [48]:
merged_death_rent.drop("Nom_Districte",axis=1,inplace=True)
merged_death_rent.drop("Nom_Barri",axis=1,inplace=True)

In [50]:
danger_data = merged_death_rent